apiVersion: v1
kind: Service
metadata:
  name: mern-client
  namespace: mern-app
spec:
  selector:
    app: mern-client
  ports:
  - port: 3000
    targetPort: {{ .Values.client.port }}
  type: LoadBalancer