apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-client
spec:
  selector:
    matchLabels:
      app: mern-client
  replicas: 1
  template:
    metadata:
      labels:
        app: mern-client
    spec:
      containers:
        - name: mern-client
          image: dali917/mern-client:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: http://mern-server:5000
